### ISSUE TITLE
Set attributes for each agent during initialisation (plan algorithm)

### ISSUE THREAD

**Issue by osbornejr** [agentsoz/bdi-abm-integration#59]
Ultimately we want to be able to define a scenario_matsim_plans.xml entirely by the inputs to the plan algorithm. This means that each attribute/parameter needs to be set for an agent up front. 

The distribution of different attributes over and within the subgroups should be defined in a new input file(s).

**Comment by dhixsingh** [comment]
Ideally we should set this up so that the population could be appended to using new distributions. So for instance if down the track I get a new distribution for evacuation places, then I would like to just remove the existing attribute for evac place and replace it with new values. Same for the other attributes. This would also allow us to take existing MATSim population files and convert them to BDI populations.

**Comment by osbornejr** [comment]
In place as of 55150ffeeb8044d6ec8369092901bd60657cd310. Still need to make assignment of dependents more intelligent (#61), and make evac/invac preferences contain a list of options (possibly ranked) (see #62). At the moment these preferences are the same for all agents, as there is a) not proper data in the input shapefile to assign these and b) not a full picture of how the LeaveNow plan will interpret these-- see #58.
